### ISSUE TITLE
Different errors for YAJL_C vs Python backends

### ISSUE THREAD

**Issue by dlafreniere** [ICRAR/ijson#65]
I don't know if all backends are supposed to behave the same, but I found that the backends treat incomplete json parsing differently.

**Describe the bug**
Python backend throws `ijson.backends.python.UnexpectedSymbol` whereas YAJL_C backend throws `ijson.common.IncompleteJSONError`

**How to reproduce**

Provide both code and a small JSON document that triggers the problem.

```python
import ijson.backends.yajl2_c as ijsonC
import ijson.backends.python as ijsonPy

invalid_json = b'{ array: [{},]'; 
parser = ijsonC.parse(invalid_json)
# parser = ijsonPy.parse(invalid_json)

for (i, (prefix, event, _value)) in enumerate(parser):
    print(event)
```
output (c)
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    for (i, (prefix, event, _value)) in enumerate(parser):
ijson.common.IncompleteJSONError: lexical error: invalid char in json text.
                                     { array: [{},]
                     (right here) ------^
```
output (py)
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    for (i, (prefix, event, _value)) in enumerate(parser):
  File "/usr/local/lib/python3.8/site-packages/ijson-3.1.4-py3.8-macosx-10.15-x86_64.egg/ijson/utils.py", line 55, in coros2gen
    f.send(value)
  File "/usr/local/lib/python3.8/site-packages/ijson-3.1.4-py3.8-macosx-10.15-x86_64.egg/ijson/backends/python.py", line 44, in utf8_encoder
    send(sdata)
  File "/usr/local/lib/python3.8/site-packages/ijson-3.1.4-py3.8-macosx-10.15-x86_64.egg/ijson/backends/python.py", line 103, in Lexer
    send((discarded + match.start(), lexeme))
  File "/usr/local/lib/python3.8/site-packages/ijson-3.1.4-py3.8-macosx-10.15-x86_64.egg/ijson/backends/python.py", line 238, in parse_value
    raise UnexpectedSymbol(symbol, pos)
ijson.backends.python.UnexpectedSymbol: Unexpected symbol 'array' at 2
```
**Expected behaviour**
Python backend should throw `ijson.common.IncompleteJSONError`

**Execution information**
 - Python version [3.8]
 - ijson version [3.1.4]
 - ijson backend (if applies) [yajl2_c + python]
 - ijson installation method [pip]
 - OS [osx 10.15]

**Comment by rtobar** [comment]
Thanks @dlafreniere for the thorough report.

I think in principle you'd indeed expect the errors to be fairly similar regardless of the backend; however in practice different backends have different capabilities and architectures, so the exceptions they raise might not always be the same. In your user code I think the best you can do is to expect an ijson.JSONError, the common type for all ijson-related exceptions. Note that other than printing its message and aborting the parsing, there's little you can do about it, regardless of the underlying cause of the error is.

Having said that, and about the case you presented: my expectation would probably be that the `yajl2_c` backend should throw something like `UnexpectedSymbol` rather than `IncompleteJSONError`, and not the other way around. A matter of preference probably, and like I said nothing substantial changes anyway other than the type of exception you see printed on the screen.

Also, in the case of error, the only information we get from the yajl library is an error message (a string), with no structured indication (unless we parse the error string, which I'd rather not do) of what the error exactly is; the only thing we can do then is to raise the same exception type regardless of the actual cause for error.

To wrap up:
 * Errors cannot be equally identified across backends
 * Hence, different backends might raise different types of exceptions for the same underlying issue

For the time being I think we'll stick to this reality. The one thing I can agree to do in the short term is to better document how errors work in the library.

Thoughts?

**Comment by dlafreniere** [comment]
Thanks for the quick response @rtobar! In my case, catching `ijson.common.JSONError` does the trick! I also came across #42  which seems semi-related.

On a related note: I'd like to move away from the python backend for performance reasons. Our runtime executes in an Alpine linux container. Do you know what packages are required for the library to find yajl? Simply having the [package](https://pkgs.alpinelinux.org/package/v3.15/main/x86_64/yajl) installed doesn't seem to work. Are [Python](https://github.com/pykler/yajl-py) [bindings](https://github.com/rtyler/py-yajl/) required?

**Comment by rtobar** [comment]
@dlafreniere good to see you got it working.

Note also that ijson has the possibility to build against an embedded copy of the yajl sources (which are linked as a git submodule under the `cextern` directory) if the `IJSON_EMBED_YAJL` environment variable is set, see the `setup.py` file for details (we use this to build the windows wheels).

**Comment by jpmckinney** [comment]
Is it possible the submodule was not checked out when packaging versions > 3.1.1? I see errors like this:

<details>

```
Collecting ijson
  Using cached ijson-3.1.4.tar.gz (56 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/james/.pyenv/versions/3.8.12/envs/cardinal/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_0e86794b5bd84668b4b7b35ae1c28d40/setup.py'"'"'; __file__='"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_0e86794b5bd84668b4b7b35ae1c28d40/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-pip-egg-info-1ptil324
         cwd: /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_0e86794b5bd84668b4b7b35ae1c28d40/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_0e86794b5bd84668b4b7b35ae1c28d40/setup.py", line 107, in <module>
        yajl_sources = patch_yajl_sources()
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_0e86794b5bd84668b4b7b35ae1c28d40/setup.py", line 93, in patch_yajl_sources
        shutil.copytree(os.path.join('cextern', 'yajl'), patched_sources)
      File "/Users/james/.pyenv/versions/3.8.12/lib/python3.8/shutil.py", line 555, in copytree
        with os.scandir(src) as itr:
    FileNotFoundError: [Errno 2] No such file or directory: 'cextern/yajl'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a8/da/f4b5fda308b60c6c31aa4203f20133a3b5b472e41c0907bc14b7c555cde2/ijson-3.1.4.tar.gz#sha256=1d1003ae3c6115ec9b587d29dd136860a81a23c7626b682e2b5b12c9fd30e4ea (from https://pypi.org/simple/ijson/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ijson-3.1.3.tar.gz (56 kB)
     |████████████████████████████████| 56 kB 4.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/james/.pyenv/versions/3.8.12/envs/cardinal/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_ad6c2ff3306d4764ad7fb57948a7b04c/setup.py'"'"'; __file__='"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_ad6c2ff3306d4764ad7fb57948a7b04c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-pip-egg-info-h653bcrg
         cwd: /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_ad6c2ff3306d4764ad7fb57948a7b04c/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_ad6c2ff3306d4764ad7fb57948a7b04c/setup.py", line 107, in <module>
        yajl_sources = patch_yajl_sources()
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_ad6c2ff3306d4764ad7fb57948a7b04c/setup.py", line 93, in patch_yajl_sources
        shutil.copytree(os.path.join('cextern', 'yajl'), patched_sources)
      File "/Users/james/.pyenv/versions/3.8.12/lib/python3.8/shutil.py", line 555, in copytree
        with os.scandir(src) as itr:
    FileNotFoundError: [Errno 2] No such file or directory: 'cextern/yajl'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6b/78/c3144ac57cee06ccd7d6de8e99f9ac60812743a488878fc57fd586fd2f3f/ijson-3.1.3.tar.gz#sha256=d29977f7235b5bf83c372825c6abd8640ba0e3a8e031d3ffc3b63deaf6ae1487 (from https://pypi.org/simple/ijson/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ijson-3.1.2.post0.tar.gz (55 kB)
     |████████████████████████████████| 55 kB 13.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/james/.pyenv/versions/3.8.12/envs/cardinal/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_41b9c2d4678a4935941a54703cdd38d3/setup.py'"'"'; __file__='"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_41b9c2d4678a4935941a54703cdd38d3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-pip-egg-info-ih3lz5me
         cwd: /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_41b9c2d4678a4935941a54703cdd38d3/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_41b9c2d4678a4935941a54703cdd38d3/setup.py", line 107, in <module>
        yajl_sources = patch_yajl_sources()
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_41b9c2d4678a4935941a54703cdd38d3/setup.py", line 93, in patch_yajl_sources
        shutil.copytree(os.path.join('cextern', 'yajl'), patched_sources)
      File "/Users/james/.pyenv/versions/3.8.12/lib/python3.8/shutil.py", line 555, in copytree
        with os.scandir(src) as itr:
    FileNotFoundError: [Errno 2] No such file or directory: 'cextern/yajl'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/27/43/6fa1ca1342bf3ad403842f8111134cdf5d77b1e413c50e66f3bbfb0d0663/ijson-3.1.2.post0.tar.gz#sha256=04fd8ebb8edb39db81f49b75b101d1e2a4d0728460e253fd9c98e3e17f9caa16 (from https://pypi.org/simple/ijson/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ijson-3.1.2.tar.gz (53 kB)
     |████████████████████████████████| 53 kB 5.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/james/.pyenv/versions/3.8.12/envs/cardinal/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_f176de9b4bcf4504b6813bc2be2ac0b1/setup.py'"'"'; __file__='"'"'/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_f176de9b4bcf4504b6813bc2be2ac0b1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-pip-egg-info-f0i29ypn
         cwd: /private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_f176de9b4bcf4504b6813bc2be2ac0b1/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_f176de9b4bcf4504b6813bc2be2ac0b1/setup.py", line 107, in <module>
        yajl_sources = patch_yajl_sources()
      File "/private/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/pip-install-_x3reay_/ijson_f176de9b4bcf4504b6813bc2be2ac0b1/setup.py", line 93, in patch_yajl_sources
        shutil.copytree(os.path.join('cextern', 'yajl'), patched_sources)
      File "/Users/james/.pyenv/versions/3.8.12/lib/python3.8/shutil.py", line 555, in copytree
        with os.scandir(src) as itr:
    FileNotFoundError: [Errno 2] No such file or directory: 'cextern/yajl'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/48/b7/a5213e5b0dcff7369af2f0ee1eb3f41cda575ca65944a4aa193a9b4bc077/ijson-3.1.2.tar.gz#sha256=401bdca19bcc7f89780e37d7b70671d40666999dac3e4b2c42a7cddd8b0891c7 (from https://pypi.org/simple/ijson/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading ijson-3.1.1-py3-none-any.whl (25 kB)
Installing collected packages: ijson
  Attempting uninstall: ijson
    Found existing installation: ijson 3.1.4
    Uninstalling ijson-3.1.4:
      Successfully uninstalled ijson-3.1.4
Successfully installed ijson-3.1.1
WARNING: You are using pip version 21.1.1; however, version 22.3 is available.
You should consider upgrading via the '/Users/james/.pyenv/versions/3.8.12/envs/cardinal/bin/python3.8 -m pip install --upgrade pip' command.
```

</details>

**Comment by rtobar** [comment]
@jpmckinney the submodule was added in 3.1.1 indeed, but since its introduction it's never been included in the source distributions of ijson. The idea was to use it internally to build the binary wheels for Windows and MacOS, which is what we're doing.

Note that the `IJSON_EMBED_YAJL` mechanism isn't mentioned in the public documentation, so I don't think any big expectations are broken. It seems `pip` supports checking out git repos with submodules, so if you need building ijson with `IJSON_EMBED_YAJL`  you'll can do `IJSON_EMBED_YAJL=1 pip install -v git+https://github.com/ICRAR/ijson@v3.1.4`.

I'm unsure whether I'd like to ship the ijson source distributions with the embedded yajl sources, I could have a look at what other projects do and decide based on that.

**Comment by jpmckinney** [comment]
Aha, sounds good. Yes, I built from source with a local checkout of the submodule instead.
